# ~/.config/alacritty/alacritty.toml
[window]
opacity = 0.85
decorations = "None"
dynamic_title = true
padding = { x = 1, y = 1 }

[font]
size = 11.0
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }

[cursor]
style = { shape = "Beam", blinking = "Always" }

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.cursor]
text = "CellBackground"
cursor = "#03EDF9"

[colors.normal]
black = "#011627"
red = "#FE4450"
green = "#72F1B8"
yellow = "#FEDE5D"
blue = "#03EDF9"
magenta = "#FF7EDB"
cyan = "#03EDF9"
white = "#FFFFFF"

[colors.bright]
black = "#575656"
red = "#FE4450"
green = "#72F1B8"
yellow = "#FEDE5D"
blue = "#03EDF9"
magenta = "#FF7EDB"
cyan = "#03EDF9"
white = "#FFFFFF"
